---
abstract: 'A quick and dirty wrapper around DotCloud::Environment'
author:
  - 'Ben van Staveren <madcat@cpan.org>'
build_requires:
  Module::Build: 0.38
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Dotcloud
requires:
  DotCloud::Environment: 0
  Mojo::Base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/benvanstaveren/mojolicious-plugin-dotcloud/issues
  repository: git://github.com/benvanstaveren/mojolicious-plugin-dotcloud.git
version: 1.01
